Repository fga-gpp-mds/2018.1-Reabilitacao-Motora, pull requests merged in 2018-04, with the labels that each got.

#71 Protótipo de Alta Fidelidade.
  docs/wiki/Prototipo.md
Labels: Agil, Atenção Necessária, Documentação, Em Atraso, Front-End, MDS, Noob

#82 Adicionando design a pagina index de documentos no github.io
  documentos.html
  index.html
Labels: Aprimoramento, Documentação, EPS, Front-End

#91 Criação do Roadmap do DevOps + Atualização dos docs de EPS
  docs/wiki/RoadmapDevOps.md
  docs/wiki/Termo-Abertura-Projeto.md
Labels: DevOps, EPS, Ágil

#92 Adição de políticas de PR e Issue
  docs/imagens/Daily/Sprint03.png
  docs/imagens/Tutoriais/Tutorial_Issue_01.png
  docs/imagens/Tutoriais/Tutorial_Issue_02.png
  docs/imagens/Tutoriais/Tutorial_Issue_03.png
  docs/imagens/Tutoriais/Tutorial_Issue_04.png
  docs/imagens/Tutoriais/Tutorial_Issue_05.png
  docs/imagens/Tutoriais/Tutorial_Issue_06.png
  docs/imagens/Tutoriais/Tutorial_Issue_07.png
  docs/imagens/Tutoriais/Tutorial_Issue_08.png
  docs/imagens/Tutoriais/Tutorial_Issue_09.png
  docs/imagens/Tutoriais/Tutorial_PullRequest_01.png
  docs/imagens/Tutoriais/Tutorial_PullRequest_02.png
  docs/imagens/Tutoriais/Tutorial_PullRequest_03.png
  docs/imagens/Tutoriais/Tutorial_PullRequest_04.png
  docs/imagens/Tutoriais/Tutorial_PullRequest_05.png
  docs/imagens/Tutoriais/Tutorial_PullRequest_06.png
  docs/imagens/Tutoriais/Tutorial_PullRequest_07.png
  docs/imagens/Tutoriais/Tutorial_PullRequest_08.png
  docs/policies/issue.md
  docs/policies/pull_request.md
  docs/sprints/Planejamento-Sprint-4.md
  docs/sprints/Resultado-Sprint-3.md
  docs/wiki/roadmap_Scrum_Master.md
Labels: Documentação, EPS, MDS, Treinamentos

#93 Criando e iniciando versão 1.0
  docs/wiki/canvas.md
Labels: Aprimoramento, Documentação, EPS, Em Atraso

#114 Criando documento da EAP com o documento desenvolvido no google drive
  docs/wiki/eap.md
Labels: Aprimoramento, Atenção Necessária, Documentação, EPS, Ágil

#118 Criar demonstração de viabilidade técnica dos acoplamentos
  TCP/.gitignore
  TCP/Assets/network.unity
  TCP/Assets/network.unity.meta
  TCP/Assets/networkSocket.cs
  TCP/Assets/networkSocket.cs.meta
  TCP/ProjectSettings/AudioManager.asset
  TCP/ProjectSettings/ClusterInputManager.asset
  TCP/ProjectSettings/DynamicsManager.asset
  TCP/ProjectSettings/EditorBuildSettings.asset
  TCP/ProjectSettings/EditorSettings.asset
  TCP/ProjectSettings/GraphicsSettings.asset
  TCP/ProjectSettings/InputManager.asset
  TCP/ProjectSettings/NavMeshAreas.asset
  TCP/ProjectSettings/NavMeshLayers.asset
  TCP/ProjectSettings/NetworkManager.asset
  TCP/ProjectSettings/Physics2DSettings.asset
  TCP/ProjectSettings/ProjectSettings.asset
  TCP/ProjectSettings/ProjectVersion.txt
  TCP/ProjectSettings/QualitySettings.asset
  TCP/ProjectSettings/TagManager.asset
  TCP/ProjectSettings/TimeManager.asset
  TCP/ProjectSettings/UnityConnectSettings.asset
  TCP/echo.py
Labels: Arquitetura, C#, Ponto Crítico, Python

#119 Adicionando EVM
  docs/imagens/EVM/Custos_do_Projeto.png
  docs/imagens/EVM/EVM_Sprint00.png
  docs/imagens/EVM/EVM_Sprint01.png
  docs/imagens/EVM/EVM_Sprint02.png
  docs/imagens/EVM/EVM_Sprint03.png
  docs/imagens/EVM/EVM_Sprint04.png
  docs/imagens/EVM/EVM_Sprint05.png
  docs/imagens/EVM/EVM_Sprint06.png
  docs/imagens/EVM/Grafico_CPI_SPI.png
  docs/imagens/EVM/Grafico_CV_SV.png
  docs/imagens/EVM/Grafico_PV_EV_AC.png
  docs/wiki/EVM.md
Labels: Documentação, EPS

#121 Adicionando Product Canvas para R1.
  docs/product_canvas/Product canvas.png
Labels: Documentação, EPS, MDS

#123 Resultado Sprint 05 e revisão de docs importantes
  docs/imagens/Burndown/Sprint_05.png
  docs/imagens/Daily/Sprint05.png
  docs/imagens/Quadro de Conhecimento/Quadro_Conhecimento_05.png
  docs/sprints/Resultado-Sprint-5.md
  docs/wiki/Commits.md
  docs/wiki/Termo-Abertura-Projeto.md
Labels: Documentação, MDS

#124 Tradução das planilhas de ata de reuniao e dojo para markdown
  docs/wiki/Atas-Reuniao.md
  docs/wiki/AtasDojo.md
Labels: Aprimoramento, Documentação, EPS, Em Atraso

#122 US07 - Cadastrar Paciente
  Reabilitacao-Motora/Assets/Plugins/fisiotech.db
  Reabilitacao-Motora/Assets/Scenes/HomeMenu.unity
  Reabilitacao-Motora/Assets/Scenes/HomeMenu.unity.meta
  Reabilitacao-Motora/Assets/Scenes/Menu.unity
  Reabilitacao-Motora/Assets/Scenes/NewPatient.unity
  Reabilitacao-Motora/Assets/Scenes/NewPhysiotherapist.unity
  Reabilitacao-Motora/Assets/Scenes/NewPhysiotherapist.unity.meta
  Reabilitacao-Motora/Assets/Scenes/Patient.unity
  Reabilitacao-Motora/Assets/Scenes/Patients.unity
  Reabilitacao-Motora/Assets/Scenes/Sessions.unity
  Reabilitacao-Motora/Assets/Scenes/sucessRegister.unity
  Reabilitacao-Motora/Assets/Scenes/sucessRegister.unity.meta
  Reabilitacao-Motora/Assets/Scripts/DataBase/DataBaseComponent.cs
  Reabilitacao-Motora/Assets/Scripts/DataBase/SQL/fisico.sql
  Reabilitacao-Motora/Assets/Scripts/DataBase/SQL/popula.sql
  Reabilitacao-Motora/Assets/Scripts/DataBase/TableNameColumn.cs
  Reabilitacao-Motora/Assets/Scripts/DataBase/Tables/Pessoa.cs
  Reabilitacao-Motora/Assets/Scripts/DataBase/Tables/Telefone.cs
  Reabilitacao-Motora/Assets/Scripts/Menu/Flow.cs
  Reabilitacao-Motora/Assets/Scripts/Patient.meta
  Reabilitacao-Motora/Assets/Scripts/Patient/createPatient.cs
  Reabilitacao-Motora/Assets/Scripts/Patient/createPatient.cs.meta
  Reabilitacao-Motora/ProjectSettings/EditorBuildSettings.asset
  Reabilitacao-Motora/ProjectSettings/ProjectSettings.asset
  Reabilitacao-Motora/ProjectSettings/ProjectVersion.txt
  docs/banco_de_dados/Diagrama_Entidade_Relacionamento.brM
  docs/banco_de_dados/Diagrama_Entidade_Relacionamento.png
  docs/banco_de_dados/LOGICO.brM
  docs/banco_de_dados/Modelo_Entidade_Relacionamento.pdf
  docs/banco_de_dados/Modelo_Logico.png
Labels: C#, MDS, Stack Overflow

#127 Documento de Visão
  docs/wiki/Documento-de-Visão.md
Labels: Documentação, MDS

#129 Integração Contínua (Build)
  .gitignore
  .travis.yml
  Reabilitacao-Motora/Assets/Editor.meta
  Reabilitacao-Motora/Assets/Editor/TravisBuildSceneSelector.cs
  Reabilitacao-Motora/Assets/Editor/TravisBuildSceneSelector.cs.meta
  Reabilitacao-Motora/Assets/Scripts/travis_build.sh
  Reabilitacao-Motora/Assets/Scripts/travis_build.sh.meta
  Reabilitacao-Motora/Assets/Scripts/travis_install.sh
  Reabilitacao-Motora/Assets/Scripts/travis_install.sh.meta
  Reabilitacao-Motora/Assets/Scripts/travis_tests.sh
  Reabilitacao-Motora/Assets/Scripts/travis_tests.sh.meta
  Reabilitacao-Motora/Assets/Tests.meta
  Reabilitacao-Motora/Assets/Tests/Editor.meta
  Reabilitacao-Motora/Assets/Tests/Editor/SampleTest.cs
  Reabilitacao-Motora/Assets/Tests/Editor/SampleTest.cs.meta
  Reabilitacao-Motora/ProjectSettings/ProjectSettings.asset
Labels: DevOps, Ponto Crítico

#130 Corrigir Documento de Arquitetura
  docs/imagens/Arquitetura/der.png
  docs/imagens/Arquitetura/diagrama.png
  docs/imagens/Arquitetura/kinect.png
  docs/imagens/Arquitetura/logico.png
  docs/wiki/Documento-de-Arquitetura.md
Labels: Arquitetura, Atenção Necessária, Documentação, MDS, Noob

#139 Alterando gráfico do EVM
  docs/imagens/EVM/Grafico_CPI_SPI.png
  docs/imagens/EVM/Grafico_CV_SV.png
  docs/imagens/EVM/Grafico_PV_EV_AC.png
  docs/imagens/Quadro de Conhecimento/Screenshot_1.png
  docs/sprints/Planejamento-Sprint-0.md
  docs/sprints/Planejamento-Sprint-1.md
  docs/sprints/Planejamento-Sprint-2.md
  docs/sprints/Planejamento-Sprint-3.md
  docs/sprints/Planejamento-Sprint-4.md
  docs/sprints/Planejamento-Sprint-5.md
  docs/sprints/Resultado-Sprint-1.md
  docs/sprints/Resultado-Sprint-4.md
  docs/sprints/Resultado-Sprint-5.md
  docs/wiki/Documento-de-Visão.md
  docs/wiki/EVM.md
Labels: Documentação, EPS
