Repository fga-gpp-mds/2018.1-Reabilitacao-Motora, pull requests merged in 2018-06, with the labels that each got.

#200 Planejamento/Resultado/Correções dos docs das sprints 10, 11 e 12
  docs/imagens/Burndown/Sprint_11.png
  docs/imagens/Daily/Sprint11.png
  docs/imagens/Quadro de Conhecimento/Quadro_Conhecimento_11.png
  docs/imagens/Quadro de Praticas Ageis/Quadro_de_Praticas_Ageis_Sprint11.png
  docs/imagens/Retrospectiva/Retrospectiva_Sprint11.png
  docs/sprints/Planejamento-Sprint-11.md
  docs/sprints/Planejamento-Sprint-12.md
  docs/sprints/Resultado-Sprint-10.md
  docs/sprints/Resultado-Sprint-11.md
Labels: Documentação, EPS

#202 Refatorar documento de arquitetura
  TCP/.gitignore
  TCP/Assets/network.unity
  TCP/Assets/network.unity.meta
  TCP/Assets/networkSocket.cs
  TCP/Assets/networkSocket.cs.meta
  TCP/ProjectSettings/AudioManager.asset
  TCP/ProjectSettings/ClusterInputManager.asset
  TCP/ProjectSettings/DynamicsManager.asset
  TCP/ProjectSettings/EditorBuildSettings.asset
  TCP/ProjectSettings/EditorSettings.asset
  TCP/ProjectSettings/GraphicsSettings.asset
  TCP/ProjectSettings/InputManager.asset
  TCP/ProjectSettings/NavMeshAreas.asset
  TCP/ProjectSettings/NavMeshLayers.asset
  TCP/ProjectSettings/NetworkManager.asset
  TCP/ProjectSettings/Physics2DSettings.asset
  TCP/ProjectSettings/ProjectSettings.asset
  TCP/ProjectSettings/ProjectVersion.txt
  TCP/ProjectSettings/QualitySettings.asset
  TCP/ProjectSettings/TagManager.asset
  TCP/ProjectSettings/TimeManager.asset
  TCP/ProjectSettings/UnityConnectSettings.asset
  TCP/echo.py
  docs/imagens/Arquitetura/Diagrama_geral_de_arquitetura.png
  docs/wiki/Documento-de-Arquitetura.md
Labels: Documentação, MDS

#223 Corrigindo bug de Paciente Cadastrado no Menu de Ajuda de Criar Novo Paciente
  Reabilitacao-Motora/Assets/Scenes/HelpExercise.unity
  Reabilitacao-Motora/Assets/Scenes/HelpPatient.unity
Labels: Bug

#222 Adição dos documentos de fechamento da Sprint 12 e planejamento da Sprint 13
  docs/imagens/Burndown/Sprint_12.png
  docs/imagens/Daily/Sprint12.png
  docs/imagens/Quadro de Conhecimento/Quadro_Conhecimento_12.png
  docs/imagens/Quadro de Praticas Ageis/Quadro_de_Praticas_Ageis_Sprint12.png
  docs/imagens/Retrospectiva/Restrospectiva_Sprint12.png
  docs/sprints/Planejamento-Sprint-13.md
  docs/sprints/Resultado-Sprint-12.md
Labels: Documentação, EPS

#228 Adicionando popup de erro no cadastro de fisioterapeutas
  Reabilitacao-Motora/Assets/Scenes/NewPhysiotherapist.unity
  Reabilitacao-Motora/Assets/Scripts/ColorManager.cs
  Reabilitacao-Motora/Assets/Scripts/Instantiations/Movement/createMovement.cs
  Reabilitacao-Motora/Assets/Scripts/Instantiations/Patient/createPatient.cs
  Reabilitacao-Motora/Assets/Scripts/Instantiations/Physiotherapist/createPhysiotherapist.cs
  Reabilitacao-Motora/Assets/Scripts/Menu/PopUpSpawnerValidation.cs
  Reabilitacao-Motora/Assets/StreamingAssets/fisiotech.db
  Reabilitacao-Motora/Assets/StreamingAssets/test_fisiotech.db
  Reabilitacao-Motora/Assets/Tests/Editor/TestCreateMovement.cs
  Reabilitacao-Motora/Assets/Tests/Editor/TestCreatePatient.cs
  Reabilitacao-Motora/Assets/Tests/TestMenu/FullRandomTests.cs
  Reabilitacao-Motora/ProjectSettings/EditorBuildSettings.asset
  Reabilitacao-Motora/ProjectSettings/ProjectSettings.asset
Labels: Aprimoramento, Bug

#231 Botão de retorno não funciona - Tela de movimento
  Reabilitacao-Motora/Assets/Scenes/Graphs3.unity
  Reabilitacao-Motora/ProjectSettings/ProjectSettings.asset
Labels: Bug, MDS, Noob

#230 Adicionando popup que informa erros no cadastro de paciente
  Reabilitacao-Motora/Assets/Scenes/NewPatient.unity
  Reabilitacao-Motora/Assets/Scenes/NewPhysiotherapist.unity
  Reabilitacao-Motora/Assets/Scripts/Instantiations/Patient/createPatient.cs
  Reabilitacao-Motora/Assets/Scripts/Instantiations/Physiotherapist/createPhysiotherapist.cs
  Reabilitacao-Motora/Assets/Scripts/Menu/PopUpSpawnerValidation.cs
  Reabilitacao-Motora/Assets/StreamingAssets/fisiotech.db
  Reabilitacao-Motora/Assets/StreamingAssets/test_fisiotech.db
  Reabilitacao-Motora/Assets/Tests/Editor/TestCreatePatient.cs
Labels: Aprimoramento, Bug, Noob

#237 Popup de informação na tela de cadastro de paciente abaixo do layout lateral
  Reabilitacao-Motora/Assets/Scenes/NewPatient.unity
  Reabilitacao-Motora/Assets/Scripts/Instantiations/Patient/instanciatePatient.cs
  Reabilitacao-Motora/Assets/StreamingAssets/fisiotech.db
Labels: Bug, Noob

#196 Correção de bugs UDP
  .gitignore
  Reabilitacao-Motora/Assets/InitTestScene636639678355417056.unity.meta
  Reabilitacao-Motora/Assets/Scenes/ChoiceSensor.unity
  Reabilitacao-Motora/Assets/Scenes/RealtimeGraphKinectPatient.unity
  Reabilitacao-Motora/Assets/Scenes/RealtimeGraphKinectPatient.unity.meta
  Reabilitacao-Motora/Assets/Scenes/RealtimeGraphUDPPatient.unity
  Reabilitacao-Motora/Assets/Scenes/RealtimeGraphUDPPhysio.unity
  Reabilitacao-Motora/Assets/Scenes/RealtimeGraphUDPPhysio.unity.meta
  Reabilitacao-Motora/Assets/Scripts/Buttons/ChoiceSensorBt.cs
  Reabilitacao-Motora/Assets/Scripts/Buttons/GraphsUDPBt.cs
  Reabilitacao-Motora/Assets/Scripts/Buttons/GraphsUDPBt.cs.meta
  Reabilitacao-Motora/Assets/Scripts/Buttons/RealtimeBackBt.cs.meta
  Reabilitacao-Motora/Assets/Scripts/Graphs/MoveByUDP.cs
  Reabilitacao-Motora/Assets/Scripts/Graphs/UDPClient.cs
  Reabilitacao-Motora/Assets/Scripts/Instantiations/Exercise/createExercise.cs
  Reabilitacao-Motora/Assets/Scripts/Instantiations/Movement/createMovement.cs
  Reabilitacao-Motora/Assets/Scripts/Instantiations/Patient/createPatient.cs
  Reabilitacao-Motora/Assets/Scripts/Instantiations/Physiotherapist/createPhysiotherapist.cs
  Reabilitacao-Motora/Assets/StreamingAssets.meta
  Reabilitacao-Motora/Assets/StreamingAssets/test_fisiotech.db.meta
  Reabilitacao-Motora/Assets/Tests/TestMenu/TestCreate.cs
  Reabilitacao-Motora/Assets/Tests/TestMenu/TestDelete.cs
  Reabilitacao-Motora/Assets/Tests/TestMenu/TestFlow.cs
  Reabilitacao-Motora/ProjectSettings/GraphicsSettings.asset
  UDP/receiveUdp.py
  UDP/sendUdp.py
Labels: Aprimoramento, Bug, MDS

#242 Atualizar documentação referente à identidade visual.
  docs/identidade_visual.md
Labels: Documentação, MDS

#245 Adicionando popup para informar erro no login
  Reabilitacao-Motora/Assets/Scenes/Login.unity
  Reabilitacao-Motora/Assets/Scripts/Menu/Login.cs
  Reabilitacao-Motora/Assets/StreamingAssets/fisiotech.db.meta
Labels: C#, Front-End, MDS, Noob

#252 Corrigindo hint na navbar do github pages
  css/creative.css
Labels: Aprimoramento, EPS, Front-End

#262 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Aprimoramento, Documentação

#284 Redimensionando e alinhando botões na scene de escolher sensor
  Reabilitacao-Motora/Assets/Scenes/ChoiceSensor.unity
Labels: Bug

#288 Campo de usuário e senha do fisioterapeuta sem limite de caracteres
  Reabilitacao-Motora/Assets/Scenes/Login.unity
  Reabilitacao-Motora/Assets/Scenes/NewPhysiotherapist Adm.unity
  Reabilitacao-Motora/Assets/Scenes/NewPhysiotherapist Common.unity
Labels: Bug

#295 Correção Campo de Músculos Trabalhados
  Reabilitacao-Motora/Assets/Scenes/NewMovement.unity
Labels: Bug

#299 Nfr framework
  docs/imagens/NFR/Confiabilidade.jpg
Labels: Aprimoramento, Documentação

#289 Privilégios Super Administrador
  Reabilitacao-Motora/Assets/Scenes/Login.unity
  Reabilitacao-Motora/Assets/Scenes/Menu.unity
  Reabilitacao-Motora/Assets/Scenes/NewPhysiotherapist Adm.unity
  Reabilitacao-Motora/Assets/Scenes/Physiotherapist.unity
  Reabilitacao-Motora/Assets/Scripts/Buttons/NewPhysiotherapistAdmBt.cs
  Reabilitacao-Motora/Assets/Scripts/Buttons/NewPhysiotherapistAdmBt.cs.meta
  Reabilitacao-Motora/Assets/Scripts/Buttons/NewPhysiotherapistBt.cs
  Reabilitacao-Motora/Assets/Scripts/Instantiations/Physiotherapist/createPhysiotherapist.cs
  Reabilitacao-Motora/Assets/Scripts/Menu/AdmOrNot.cs
  Reabilitacao-Motora/Assets/Scripts/Menu/AdmOrNot.cs.meta
  Reabilitacao-Motora/Assets/Scripts/Menu/Login.cs
  Reabilitacao-Motora/Assets/StreamingAssets/fisiotech.db
  Reabilitacao-Motora/Assets/StreamingAssets/test_fisiotech.db.meta
  Reabilitacao-Motora/Assets/Tests/TestMenu/TestCreate.cs
Labels: Bug

#285 Campo telefone do fisioterapeuta e paciente sem limitador e desformatado
  Reabilitacao-Motora/Assets/Scenes/NewPatient.unity
  Reabilitacao-Motora/Assets/Scenes/NewPhysiotherapist Adm.unity
  Reabilitacao-Motora/Assets/Scenes/NewPhysiotherapist Common.unity
Labels: Bug

#307 Corrigindo mensagem de popup na tela de login
  Reabilitacao-Motora/Assets/Scenes/Login.unity
Labels: Aprimoramento, C#, Front-End

#309 Títulos de telas
  Reabilitacao-Motora/Assets/Scenes/MovementsToExercise.unity
  Reabilitacao-Motora/Assets/Scenes/MovementsToReview.unity
  Reabilitacao-Motora/Assets/Scenes/NewSession.unity
  Reabilitacao-Motora/Assets/Scenes/Patient.unity
  Reabilitacao-Motora/Assets/Scenes/Session.unity
  Reabilitacao-Motora/Assets/Scenes/Sessions.unity
  Reabilitacao-Motora/ProjectSettings/ProjectVersion.txt
Labels: Bug

#312 Corrigido o campo de observação do Paciente
  Reabilitacao-Motora/Assets/Scenes/Patient.unity
  Reabilitacao-Motora/Assets/Scenes/UpdatePatient.unity
Labels: Bug

#286 Correçao de todos os bugs referentes às issues 274, 277 e 278
  Reabilitacao-Motora/Assets/Scenes/ExercisesToReview.unity
  Reabilitacao-Motora/Assets/Scenes/Movements.unity
  Reabilitacao-Motora/Assets/Scenes/NewPatient.unity
  Reabilitacao-Motora/Assets/Scenes/NewSession.unity
  Reabilitacao-Motora/Assets/Scenes/RealtimeGraphKinectPatient.unity
  Reabilitacao-Motora/Assets/Scenes/RealtimeGraphKinectPhysio.unity
  Reabilitacao-Motora/Assets/Scenes/RealtimeGraphUDPPatient.unity
  Reabilitacao-Motora/Assets/Scenes/RealtimeGraphUDPPhysio.unity
  Reabilitacao-Motora/Assets/Scripts/Graphs/_Joint.cs
  Reabilitacao-Motora/Assets/Scripts/Instantiations/Exercise/DeleteExerciseButton.cs
  Reabilitacao-Motora/Assets/Scripts/Instantiations/Movement/DeleteMovementButton.cs
  Reabilitacao-Motora/Assets/Scripts/Instantiations/Session/instanciateSession.cs
  Reabilitacao-Motora/Assets/StreamingAssets/fisiotech.db
  Reabilitacao-Motora/Assets/StreamingAssets/test_fisiotech.db.meta
  Reabilitacao-Motora/Assets/Tests/Editor/TestInstanciate.cs
  Reabilitacao-Motora/Assets/Tests/Editor/Test_Joint.cs
  Reabilitacao-Motora/Assets/Tests/TestMenu/TestDelete.cs
Labels: Bug, C#, Noob

#282 Consertando bug do avatar
  Reabilitacao-Motora/Assets/Scenes/Graphs1.unity
  Reabilitacao-Motora/Assets/Scenes/Graphs2.unity
  Reabilitacao-Motora/Assets/Scenes/Graphs3.unity
  Reabilitacao-Motora/Assets/Scenes/NewPhysiotherapist Adm.unity
  Reabilitacao-Motora/Assets/Scenes/RealtimeGraphKinectPatient.unity
  Reabilitacao-Motora/Assets/Scenes/RealtimeGraphKinectPhysio.unity
  Reabilitacao-Motora/Assets/Scenes/RealtimeGraphUDPPatient.unity
  Reabilitacao-Motora/Assets/Scenes/RealtimeGraphUDPPhysio.unity
  Reabilitacao-Motora/Assets/Scripts/Buttons/LoginBt.cs
  Reabilitacao-Motora/Assets/Scripts/Graphs/GenerateLineChart.cs
  Reabilitacao-Motora/Assets/Scripts/Graphs/GenerateLineChartRealTime.cs
  Reabilitacao-Motora/Assets/Scripts/Graphs/MoveByUDP.cs
  Reabilitacao-Motora/Assets/Scripts/Graphs/UDPClient.cs
  Reabilitacao-Motora/Assets/Scripts/Instantiations/Physiotherapist/createPhysiotherapist.cs
  Reabilitacao-Motora/Assets/Scripts/Menu/GlobalController.cs
  Reabilitacao-Motora/Assets/Tests/TestMenu/TestCreate.cs
  Reabilitacao-Motora/Assets/Tests/TestMenu/TestFlow.cs
  Reabilitacao-Motora/ProjectSettings/DynamicsManager.asset
  Reabilitacao-Motora/ProjectSettings/ProjectSettings.asset
  Reabilitacao-Motora/ProjectSettings/TimeManager.asset
Labels: Atenção Necessária, Bug, C#, Noob

#316 Corrigir bug do mal funcionamento do Kinect
  Reabilitacao-Motora/Assets/Scripts/Characters/AvatarChange.cs
Labels: Bug, MDS, Stack Overflow

#315 Botao de sair do aplicativo
  Reabilitacao-Motora/Assets/Scenes/CharacterMenu.unity
  Reabilitacao-Motora/Assets/Scenes/ChoiceSensor.unity
  Reabilitacao-Motora/Assets/Scenes/ClinicToMoveMenu.unity
  Reabilitacao-Motora/Assets/Scenes/EndSession.unity
  Reabilitacao-Motora/Assets/Scenes/ExercisesToReview.unity
  Reabilitacao-Motora/Assets/Scenes/Graphs1.unity
  Reabilitacao-Motora/Assets/Scenes/Graphs2.unity
  Reabilitacao-Motora/Assets/Scenes/Graphs3.unity
  Reabilitacao-Motora/Assets/Scenes/Help.unity
  Reabilitacao-Motora/Assets/Scenes/HelpExercise.unity
  Reabilitacao-Motora/Assets/Scenes/HelpMovement.unity
  Reabilitacao-Motora/Assets/Scenes/HelpMovementLabel.unity
  Reabilitacao-Motora/Assets/Scenes/HelpPatient.unity
  Reabilitacao-Motora/Assets/Scenes/HelpResults.unity
  Reabilitacao-Motora/Assets/Scenes/HelpSession.unity
  Reabilitacao-Motora/Assets/Scenes/HelpUpdate.unity
  Reabilitacao-Motora/Assets/Scenes/Login.unity
  Reabilitacao-Motora/Assets/Scenes/Menu.unity
  Reabilitacao-Motora/Assets/Scenes/Movements.unity
  Reabilitacao-Motora/Assets/Scenes/MovementsToExercise.unity
  Reabilitacao-Motora/Assets/Scenes/MovementsToReview.unity
  Reabilitacao-Motora/Assets/Scenes/NewMovement.unity
  Reabilitacao-Motora/Assets/Scenes/NewPatient.unity
  Reabilitacao-Motora/Assets/Scenes/NewPhysiotherapist Adm.unity
  Reabilitacao-Motora/Assets/Scenes/NewPhysiotherapist Common.unity
  Reabilitacao-Motora/Assets/Scenes/NewSession.unity
  Reabilitacao-Motora/Assets/Scenes/Patient.unity
  Reabilitacao-Motora/Assets/Scenes/Physiotherapist.unity
  Reabilitacao-Motora/Assets/Scenes/RealtimeGraphKinectPatient.unity
  Reabilitacao-Motora/Assets/Scenes/RealtimeGraphKinectPhysio.unity
  Reabilitacao-Motora/Assets/Scenes/RealtimeGraphUDPPatient.unity
  Reabilitacao-Motora/Assets/Scenes/Session.unity
  Reabilitacao-Motora/Assets/Scenes/Sessions.unity
  Reabilitacao-Motora/Assets/Scenes/UpdatePatient.unity
  Reabilitacao-Motora/Assets/Scenes/UpdatePhysiotherapist.unity
Labels: Front-End, MDS

#318 Removendo o id do Exercicio
  Reabilitacao-Motora/Assets/Scripts/Instantiations/Exercise/instanciateExercise.cs
Labels: Bug

#317 Criação de Label
  Reabilitacao-Motora/Assets/Scenes/GraphsExerciciosSalvosPatient.unity
  Reabilitacao-Motora/Assets/Scenes/GraphsExerciciosSalvosPatient.unity.meta
  Reabilitacao-Motora/Assets/Scenes/GraphsMovimentoPhysio.unity
  Reabilitacao-Motora/Assets/Scenes/GraphsMovimentoPhysio.unity.meta
  Reabilitacao-Motora/Assets/Scenes/GraphsReviewDuranteSessaoPatient.unity
  Reabilitacao-Motora/Assets/Scenes/GraphsReviewDuranteSessaoPatient.unity.meta
  Reabilitacao-Motora/Assets/Scenes/RealtimeGraphKinectPatient.unity
  Reabilitacao-Motora/Assets/Scenes/RealtimeGraphKinectPhysio.unity
  Reabilitacao-Motora/Assets/Scenes/RealtimeGraphUDPPatient.unity
  Reabilitacao-Motora/Assets/Scenes/RealtimeGraphUDPPhysio.unity
  Reabilitacao-Motora/Assets/Scripts/Graphs/GenerateLineChart.cs
  Reabilitacao-Motora/Assets/Scripts/Graphs/GenerateLineChartRealTime.cs
  Reabilitacao-Motora/Assets/Scripts/Graphs/Label/DrawAreaLabel.cs
  Reabilitacao-Motora/Assets/Scripts/Graphs/Label/DrawAreaLabel.cs.meta
  Reabilitacao-Motora/Assets/Scripts/Graphs/Label/Label Fisioterapeuta/CreateLabelPhysio.cs
  Reabilitacao-Motora/Assets/Scripts/Graphs/Label/Label Paciente/CreateLabelPatient.cs
  Reabilitacao-Motora/Assets/Scripts/Graphs/MoveByUDP.cs
  Reabilitacao-Motora/Assets/Scripts/Graphs/Timer.cs
  Reabilitacao-Motora/Assets/Scripts/Graphs/UDPClient.cs
  Reabilitacao-Motora/Assets/Scripts/Menu/Flow.cs
  Reabilitacao-Motora/Assets/StreamingAssets/fisiotech.db
  Reabilitacao-Motora/Assets/StreamingAssets/fisiotech.db.meta
  Reabilitacao-Motora/Assets/StreamingAssets/test_fisiotech.db.meta
  Reabilitacao-Motora/Assets/Tests/TestMenu/TestFlow.cs
  Reabilitacao-Motora/ProjectSettings/EditorBuildSettings.asset
  Reabilitacao-Motora/ProjectSettings/EditorSettings.asset
  Reabilitacao-Motora/ProjectSettings/ProjectVersion.txt
Labels: Aprimoramento, C#, Front-End, MDS, Stack Overflow

#314 Juntar a tela de observações da sessão com a de movimentos
  Reabilitacao-Motora/Assets/Scenes/MovementsToReview.unity
  Reabilitacao-Motora/Assets/Scenes/MovementsToReview.unity.meta
  Reabilitacao-Motora/Assets/Scenes/Session.unity
  Reabilitacao-Motora/Assets/Scripts/Instantiations/Movement/instanciateMovementInSession.cs
Labels: Aprimoramento, C#, Front-End

#321 Adicionando limite de range p labels não extrapolarem o grafico
  Reabilitacao-Motora/Assets/Exercicios.meta
  Reabilitacao-Motora/Assets/Movimentos.meta
  Reabilitacao-Motora/Assets/Scenes/GraphsExerciciosSalvosPatient.unity
  Reabilitacao-Motora/Assets/Scenes/GraphsMovimentoPhysio.unity
  Reabilitacao-Motora/Assets/Scenes/GraphsReviewDuranteSessaoPatient.unity
  Reabilitacao-Motora/Assets/Scenes/RealtimeGraphKinectPatient.unity
  Reabilitacao-Motora/Assets/Scenes/RealtimeGraphKinectPhysio.unity
  Reabilitacao-Motora/Assets/Scenes/RealtimeGraphUDPPatient.unity
  Reabilitacao-Motora/Assets/Scenes/RealtimeGraphUDPPhysio.unity
  Reabilitacao-Motora/Assets/Scripts/Graphs/Label/DrawAreaLabel.cs
  Reabilitacao-Motora/Assets/Scripts/Graphs/Label/Label Fisioterapeuta/InstanciateLabelsPhysio.cs
  Reabilitacao-Motora/Assets/Scripts/Graphs/Label/Label Fisioterapeuta/MoveObjectXAxisPhysio.cs
  Reabilitacao-Motora/Assets/Scripts/Graphs/Label/Label Paciente/InstanciateLabelsPatient.cs
  Reabilitacao-Motora/Assets/Scripts/Graphs/Label/Label Paciente/MoveObjectXAxisPatient.cs
  Reabilitacao-Motora/Assets/StreamingAssets/fisiotech.db.meta
Labels: Bug, C#, Noob

#322 Adicionando o planejamento da sprint 14
  docs/sprints/Planejamento-Sprint-14.md
Labels: Duplicação, EPS, Scrum Master

#324 Atualização dos eixos tornada mais fácil
  Reabilitacao-Motora/Assets/Prefabs/Graphs/RotuloFisioterapeuta.prefab
  Reabilitacao-Motora/Assets/Prefabs/Graphs/RotuloPaciente.prefab
  Reabilitacao-Motora/Assets/Scenes/RealtimeGraphUDPPhysio.unity
  Reabilitacao-Motora/Assets/Scripts/Graphs/Label/Label Fisioterapeuta/MoveIconXAxis.cs
  Reabilitacao-Motora/Assets/Scripts/Graphs/Label/Label Fisioterapeuta/MoveIconXAxis.cs.meta
  Reabilitacao-Motora/Assets/Scripts/Graphs/Label/Label Fisioterapeuta/MoveObjectXAxis.cs
  Reabilitacao-Motora/Assets/Scripts/Graphs/Label/Label Fisioterapeuta/MoveObjectXAxis.cs.meta
  Reabilitacao-Motora/Assets/Scripts/Graphs/Label/Label Paciente/MoveObjectXAxisPatient.cs
Labels: Aprimoramento, C#, Front-End, Noob

#290 Ver exercicios da sessão com bug de duplicação.
  Reabilitacao-Motora/Assets/Scenes/ExercisesToReview.unity
  Reabilitacao-Motora/Assets/Scenes/Session.unity
  Reabilitacao-Motora/Assets/Scripts/Instantiations/Movement/instanciateMovementInSession.cs
Labels: Bug

#327 Criando doc de resultado da sprint 13
  docs/imagens/Burndown/Sprint_13.png
  docs/imagens/Daily/Sprint13.png
  docs/imagens/Quadro de Praticas Ageis/Quadro_de_Praticas_Ageis_Sprint13.png
  docs/imagens/Retrospectiva/Retrospectiva_Sprint13.png
  docs/sprints/Resultado-Sprint-13.md
Labels: Documentação, EPS, Em Atraso

#330 Persistencia da escolha do tipo de sensor
  Reabilitacao-Motora/Assets/Scripts/Instantiations/Movement/createMovement.cs
  Reabilitacao-Motora/Assets/SensorChoice.cs
  Reabilitacao-Motora/ProjectSettings/ProjectSettings.asset
Labels: Aprimoramento, Bug

#332 Alinhamento de botões na escolha do personagem
  Reabilitacao-Motora/Assets/Scenes/CharacterMenu.unity
  Reabilitacao-Motora/Assets/Scripts/Buttons/ClipButtonToObject.cs
  Reabilitacao-Motora/Assets/Scripts/Buttons/ClipButtonToObject.cs.meta
Labels: Aprimoramento, Bug, Front-End

#329 Juntar a tela de pacientes com a de sessões
  Reabilitacao-Motora/Assets/Prefabs/SessionPrefab.prefab
  Reabilitacao-Motora/Assets/Scenes/Patient.unity.orig
  Reabilitacao-Motora/Assets/Scenes/Session.unity
  Reabilitacao-Motora/Assets/Scenes/Sessions.unity
  Reabilitacao-Motora/Assets/Scenes/Sessions.unity.meta
  Reabilitacao-Motora/Assets/Scripts/Buttons/SessionsBt.cs
  Reabilitacao-Motora/Assets/Scripts/Instantiations/Session/DeleteSessionButton.cs
  Reabilitacao-Motora/Assets/Tests/TestMenu/TestCreate.cs
  Reabilitacao-Motora/Assets/Tests/TestMenu/TestDelete.cs
  Reabilitacao-Motora/Assets/Tests/TestMenu/TestFlow.cs
  Reabilitacao-Motora/ProjectSettings/EditorBuildSettings.asset
Labels: Aprimoramento, C#, Front-End

#333 Criação do planejamento da sprint 15
  docs/sprints/Planejamento-Sprint-15.md
Labels: Documentação, EPS

#335 Conserto do teste InstantiateSession
  Reabilitacao-Motora/Assets/Tests/Editor/TestInstanciate.cs
Labels: Bug, Noob, Testes

#331 Refatoração das Telas de Ajuda
  Reabilitacao-Motora/Assets/Imgs/bgHelpMovement6.PNG
  Reabilitacao-Motora/Assets/Imgs/bgHelpResults1.png
  Reabilitacao-Motora/Assets/Imgs/bgHelpResults4.png
  Reabilitacao-Motora/Assets/Scenes/HelpExercise.unity
  Reabilitacao-Motora/Assets/Scenes/HelpMovementLabel.unity
  Reabilitacao-Motora/Assets/Scenes/HelpResults.unity
Labels: Bug, Noob

#337 Resultado da sprint 14
  docs/imagens/Burndown/Sprint_14.png
  docs/imagens/Daily/Sprint14.png
  docs/imagens/Quadro de Praticas Ageis/Quadro_de_Praticas_Ageis_Sprint14.png
  docs/imagens/Retrospectiva/Retrospectiva_Sprint14.png
  docs/sprints/Planejamento-Sprint-14.md
  docs/sprints/Resultado-Sprint-14.md
Labels: Aprimoramento, Documentação, Scrum Master, Ágil

#349 Trocar animações com problemas de colisão
  Reabilitacao-Motora/Assets/Actions/Man/Air Squat.fbx
  Reabilitacao-Motora/Assets/Actions/Man/Bicycle Crunch.fbx
  Reabilitacao-Motora/Assets/Actions/Man/Bicycle Crunch.fbx.meta
  Reabilitacao-Motora/Assets/Actions/Man/PrepareExerciseMan.controller
  Reabilitacao-Motora/Assets/Actions/Man/Start Bicycle Sit Up.fbx
  Reabilitacao-Motora/Assets/Actions/Man/Start Bicycle Sit Up.fbx.meta
  Reabilitacao-Motora/Assets/Actions/Woman/Douglas@Victory.fbx
  Reabilitacao-Motora/Assets/Actions/Woman/Happy.fbx
  Reabilitacao-Motora/Assets/Actions/Woman/Happy.fbx.meta
Labels: Aprimoramento, Bug

#350 Melhorias no README
  README.md
  docs/imagens/readme/soft_screenshot_1.png
Labels: Aprimoramento, Documentação

#352 Correção das Animation Controllers
  Reabilitacao-Motora/Assets/Actions/Man/PrepareExerciseMan.controller
  Reabilitacao-Motora/Assets/Actions/Woman/CharacterWoman.controller
Labels: Bug

#353 Atualizando versão do Unity no Travis
  Reabilitacao-Motora/Assets/Scripts/travis_install.sh
Labels: Aprimoramento, DevOps

#354 Distinguindo rotulo de movimento e exercicio
  Reabilitacao-Motora/Assets/Materials/Graphs/DarkGreen.mat
  Reabilitacao-Motora/Assets/Materials/Graphs/DarkGreen.mat.meta
  Reabilitacao-Motora/Assets/Materials/Graphs/Materials.meta
  Reabilitacao-Motora/Assets/Materials/Graphs/Materials/dark-green.mat
  Reabilitacao-Motora/Assets/Materials/Graphs/Materials/dark-green.mat.meta
  Reabilitacao-Motora/Assets/Materials/Graphs/Textures/dark-green.png
  Reabilitacao-Motora/Assets/Materials/Graphs/Textures/dark-green.png.meta
  Reabilitacao-Motora/Assets/Prefabs/Graphs/Grafico.prefab
  Reabilitacao-Motora/Assets/Prefabs/Graphs/RotuloFisioterapeuta.prefab
  Reabilitacao-Motora/Assets/Scenes/GraphsExerciciosSalvosPatient.unity
  Reabilitacao-Motora/Assets/Scenes/GraphsMovimentoPhysio.unity
  Reabilitacao-Motora/Assets/Scenes/GraphsReviewDuranteSessaoPatient.unity
  Reabilitacao-Motora/Assets/Scenes/Movements.unity
  Reabilitacao-Motora/Assets/Scenes/NewSession.unity
  Reabilitacao-Motora/Assets/Scenes/Patient.unity
  Reabilitacao-Motora/Assets/Scenes/RealtimeGraphKinectPatient.unity
  Reabilitacao-Motora/Assets/Scenes/RealtimeGraphKinectPhysio.unity
  Reabilitacao-Motora/Assets/Scenes/RealtimeGraphUDPPatient.unity
  Reabilitacao-Motora/Assets/Scenes/RealtimeGraphUDPPhysio.unity
  Reabilitacao-Motora/Assets/Scripts/Buttons/MovementsMesmoBt.cs
  Reabilitacao-Motora/Assets/Scripts/Buttons/MovementsMesmoBt.cs.meta
  Reabilitacao-Motora/Assets/Scripts/Graphs/Label/Label Fisioterapeuta/MoveIconXAxis.cs
  Reabilitacao-Motora/Assets/Scripts/Graphs/Label/Label Fisioterapeuta/MoveObjectXAxis.cs
Labels: Front-End

#357 Readme 2.0
  README.md
  docs/imagens/readme/Gravar_Movimento.png
  docs/imagens/readme/Produto.png
  docs/imagens/readme/Produto_Inicial.png
  docs/imagens/readme/Travis.png
  docs/imagens/readme/Unity.png
  docs/imagens/readme/drive.png
  docs/imagens/readme/git.png
  docs/imagens/readme/slack.png
  docs/imagens/readme/soft_screenshot_1.png
  docs/imagens/readme/telegram.png
  docs/imagens/readme/wpp.png
  docs/imagens/readme/zenhub.png
  docs/policies/commits.md
Labels: Aprimoramento, Documentação

#364 Resolvendo bug do botão na scene session
  Reabilitacao-Motora/Assets/Scenes/Session.unity
Labels: Bug

#367 Script para medir latência do sensor UDP
  UDP/measureUDPLatency.py
Labels: Aprimoramento, Arquitetura, EPS, Python

#369 Adaptar Aplicação para Múltiplas Resoluções
  Reabilitacao-Motora/Assets/Scenes/CharacterMenu.unity
  Reabilitacao-Motora/Assets/Scenes/ChoiceSensor.unity
  Reabilitacao-Motora/Assets/Scenes/ClinicToMoveMenu.unity
  Reabilitacao-Motora/Assets/Scenes/EndSession.unity
  Reabilitacao-Motora/Assets/Scenes/ExercisesToReview.unity
  Reabilitacao-Motora/Assets/Scenes/GraphsExerciciosSalvosPatient.unity
  Reabilitacao-Motora/Assets/Scenes/GraphsMovimentoPhysio.unity
  Reabilitacao-Motora/Assets/Scenes/GraphsReviewDuranteSessaoPatient.unity
  Reabilitacao-Motora/Assets/Scenes/Help.unity
  Reabilitacao-Motora/Assets/Scenes/HelpExercise.unity
  Reabilitacao-Motora/Assets/Scenes/HelpMovement.unity
  Reabilitacao-Motora/Assets/Scenes/HelpMovementLabel.unity
  Reabilitacao-Motora/Assets/Scenes/HelpPatient.unity
  Reabilitacao-Motora/Assets/Scenes/HelpResults.unity
  Reabilitacao-Motora/Assets/Scenes/HelpSession.unity
  Reabilitacao-Motora/Assets/Scenes/HelpUpdate.unity
  Reabilitacao-Motora/Assets/Scenes/Login.unity
  Reabilitacao-Motora/Assets/Scenes/Menu.unity
  Reabilitacao-Motora/Assets/Scenes/Movements.unity
  Reabilitacao-Motora/Assets/Scenes/MovementsToExercise.unity
  Reabilitacao-Motora/Assets/Scenes/NewMovement.unity
  Reabilitacao-Motora/Assets/Scenes/NewPatient.unity
  Reabilitacao-Motora/Assets/Scenes/NewPhysiotherapist Adm.unity
  Reabilitacao-Motora/Assets/Scenes/NewPhysiotherapist Common.unity
  Reabilitacao-Motora/Assets/Scenes/NewSession.unity
  Reabilitacao-Motora/Assets/Scenes/Patient.unity
  Reabilitacao-Motora/Assets/Scenes/Physiotherapist.unity
  Reabilitacao-Motora/Assets/Scenes/RealtimeGraphKinectPatient.unity
  Reabilitacao-Motora/Assets/Scenes/RealtimeGraphKinectPhysio.unity
  Reabilitacao-Motora/Assets/Scenes/RealtimeGraphUDPPatient.unity
  Reabilitacao-Motora/Assets/Scenes/RealtimeGraphUDPPhysio.unity
  Reabilitacao-Motora/Assets/Scenes/Session.unity
  Reabilitacao-Motora/Assets/Scenes/Session.unity.meta
  Reabilitacao-Motora/Assets/Scenes/UpdatePatient.unity
  Reabilitacao-Motora/Assets/Scenes/UpdatePhysiotherapist.unity
  Reabilitacao-Motora/Assets/Scripts/Graphs/Timer.cs
Labels: Aprimoramento, Front-End

#373 Eps docs
  docs/wiki/Post_Mortem.md
Labels: Aprimoramento, Atenção Necessária, Documentação, EPS
