Repository fga-gpp-mds/2018.1-Reabilitacao-Motora, pull requests merged in 2018-05, with the labels that each got.

#153 Planejamento das Sprint 06/07/08 e Resultado da Sprint 06
  docs/imagens/Burndown/Sprint_06.png
  docs/imagens/Daily/Sprint06.png
  docs/imagens/Daily/Sprint07.png
  docs/imagens/Quadro de Conhecimento/Quadro_Conhecimento_06.png
  docs/imagens/Quadro de Conhecimento/Quadro_Conhecimento_07.png
  docs/imagens/Quadro de Conhecimento/Screenshot_1.png
  docs/imagens/Quadro de Pareamento/Quadro_de_Pareamento.xml
  docs/imagens/Quadro de Pareamento/Quadro_de_Pareamento_Sprint06.png
  docs/imagens/Quadro de Pareamento/Quadro_de_Pareamento_Sprint07.png
  docs/imagens/Release/Burndown_Release_01.png
  docs/imagens/Retrospectiva/Retrospectiva_Sprint06.png
  docs/imagens/Retrospectiva/Retrospectiva_Sprint07.png
  docs/sprints/Planejamento-Sprint-6.md
  docs/sprints/Planejamento-Sprint-7.md
  docs/sprints/Planejamento-Sprint-8.md
  docs/sprints/Resultado-Sprint-2.md
  docs/sprints/Resultado-Sprint-3.md
  docs/sprints/Resultado-Sprint-4.md
  docs/sprints/Resultado-Sprint-5.md
  docs/sprints/Resultado-Sprint-6.md
Labels: Documentação, EPS, Scrum Master

#155 Resultado da Sprint 07
  docs/imagens/Burndown/Sprint_07.png
  docs/imagens/Quadro de Praticas Ageis/Quadro_de_Praticas_Ageis_Sprint07.png
  docs/sprints/Planejamento-Sprint-7.md
  docs/sprints/Planejamento-Sprint-8.md
  docs/sprints/Resultado-Sprint-6.md
  docs/sprints/Resultado-Sprint-7.md
Labels: Documentação, EPS, Scrum Master

#154 Criptografia
  .gitignore
  Reabilitacao-Motora/Assets/Movimentos.meta
  Reabilitacao-Motora/Assets/Movimentos/3-Carlos_Paraiba/abcd-001930.points
  Reabilitacao-Motora/Assets/Movimentos/3-Carlos_Paraiba/abcd-001930.points.meta
  Reabilitacao-Motora/Assets/Movimentos/3-Carlos_Paraiba/aopkdr12pk-095920.points
  Reabilitacao-Motora/Assets/Movimentos/3-Carlos_Paraiba/aopkdr12pk-095920.points.meta
  Reabilitacao-Motora/Assets/Movimentos/3-Carlos_Paraiba/asidmasomd-095530.points
  Reabilitacao-Motora/Assets/Movimentos/3-Carlos_Paraiba/asidmasomd-095530.points.meta
  Reabilitacao-Motora/Assets/Movimentos/3-Carlos_Paraiba/czsczx-003423.points
  Reabilitacao-Motora/Assets/Movimentos/3-Carlos_Paraiba/czsczx-003423.points.meta
  Reabilitacao-Motora/Assets/Movimentos/3-Carlos_Paraiba/ksfpoaskr91-093827.points
  Reabilitacao-Motora/Assets/Movimentos/3-Carlos_Paraiba/ksfpoaskr91-093827.points.meta
  Reabilitacao-Motora/Assets/Movimentos/3-Carlos_Paraiba/levantamento_de_garfo-235826.points
  Reabilitacao-Motora/Assets/Movimentos/3-Carlos_Paraiba/levantamento_de_garfo-235826.points.meta
  Reabilitacao-Motora/Assets/Plugins/fisiotech.db
  Reabilitacao-Motora/Assets/Scripts/Encryption.meta
  Reabilitacao-Motora/Assets/Scripts/Encryption/AES256.cs
  Reabilitacao-Motora/Assets/Scripts/Encryption/AES256.cs.meta
  Reabilitacao-Motora/Assets/Scripts/Encryption/BCrypt.cs
  Reabilitacao-Motora/Assets/Scripts/Encryption/BCrypt.cs.meta
  Reabilitacao-Motora/Assets/Scripts/Encryption/CryptPassword.cs
  Reabilitacao-Motora/Assets/Scripts/Encryption/CryptPassword.cs.meta
  Reabilitacao-Motora/Assets/Scripts/Encryption/Pepper.cs
  Reabilitacao-Motora/Assets/Scripts/Encryption/Pepper.cs.meta
  Reabilitacao-Motora/Assets/Scripts/Encryption/SHA_256.cs
  Reabilitacao-Motora/Assets/Scripts/Encryption/SHA_256.cs.meta
  Reabilitacao-Motora/Assets/Scripts/Encryption/SHA_512.cs
  Reabilitacao-Motora/Assets/Scripts/Encryption/SHA_512.cs.meta
  Reabilitacao-Motora/Assets/Scripts/Graphs/GenerateLineChart.cs
  Reabilitacao-Motora/Assets/Scripts/Graphs/GenerateLineChartRealTime.cs
  Reabilitacao-Motora/Assets/Scripts/Graphs/Label/CenterText.cs
  Reabilitacao-Motora/Assets/Scripts/Graphs/Label/CreateLabel.cs
  Reabilitacao-Motora/Assets/Scripts/Patient/Login.cs
  Reabilitacao-Motora/Assets/Scripts/Patient/createMovement.cs
  Reabilitacao-Motora/Assets/Scripts/Patient/createPhysiotherapist.cs
  Reabilitacao-Motora/ProjectSettings/ProjectVersion.txt
Labels: Aprimoramento, C#, MDS, Stack Overflow

#157 Refatoracao Identidade Visual
  Reabilitacao-Motora/Assets/Exercicios.meta
  Reabilitacao-Motora/Assets/Imgs/ajuda.png
  Reabilitacao-Motora/Assets/Imgs/ajuda.png.meta
  Reabilitacao-Motora/Assets/Imgs/bg5.png
  Reabilitacao-Motora/Assets/Imgs/bg5.png.meta
  Reabilitacao-Motora/Assets/Imgs/bgDefault5.png
  Reabilitacao-Motora/Assets/Imgs/bgDefault5.png.meta
  Reabilitacao-Motora/Assets/Imgs/bgDefault5Background.png
  Reabilitacao-Motora/Assets/Imgs/bgDefault5Background.png.meta
  Reabilitacao-Motora/Assets/Imgs/icons8-esquerda-filled-50.png
  Reabilitacao-Motora/Assets/Imgs/icons8-esquerda-filled-50.png.meta
  Reabilitacao-Motora/Assets/Imgs/icons8-flecha-50.png
  Reabilitacao-Motora/Assets/Imgs/icons8-flecha-50.png.meta
  Reabilitacao-Motora/Assets/Imgs/movimentos.png
  Reabilitacao-Motora/Assets/Imgs/movimentos.png.meta
  Reabilitacao-Motora/Assets/Imgs/paciente.png
  Reabilitacao-Motora/Assets/Imgs/paciente.png.meta
  Reabilitacao-Motora/Assets/Imgs/trash-black-shape.png
  Reabilitacao-Motora/Assets/Imgs/trash-black-shape.png.meta
  Reabilitacao-Motora/Assets/Movimentos/3-Carlos_Paraiba.meta
  Reabilitacao-Motora/Assets/Plugins/fisiotech.db
  Reabilitacao-Motora/Assets/Scenes/Clinic.unity
  Reabilitacao-Motora/Assets/Scenes/ClinicToMoveMenu.unity
  Reabilitacao-Motora/Assets/Scenes/ClinicToMoveMenu.unity.meta
  Reabilitacao-Motora/Assets/Scenes/Graphs2.unity
  Reabilitacao-Motora/Assets/Scenes/Login.unity
  Reabilitacao-Motora/Assets/Scenes/Menu.unity
  Reabilitacao-Motora/Assets/Scenes/Movements.unity
  Reabilitacao-Motora/Assets/Scenes/NewMovement.unity
  Reabilitacao-Motora/Assets/Scenes/NewPatient.unity
  Reabilitacao-Motora/Assets/Scenes/NewPhysiotherapist.unity
  Reabilitacao-Motora/Assets/Scenes/NotImplemented.unity
  Reabilitacao-Motora/Assets/Scenes/Patient.unity
  Reabilitacao-Motora/Assets/Scenes/Patients.unity
  Reabilitacao-Motora/Assets/Scenes/Physiotherapists.unity
  Reabilitacao-Motora/Assets/Scenes/RealtimeGraph.unity
  Reabilitacao-Motora/Assets/Scenes/Session.unity
  Reabilitacao-Motora/Assets/Scenes/Sessions.unity
  Reabilitacao-Motora/Assets/Scenes/SuccessRegister.unity
  Reabilitacao-Motora/Assets/Scenes/UpdatePatient.unity
  Reabilitacao-Motora/Assets/Scripts/Menu/Flow.cs
  Reabilitacao-Motora/Assets/Scripts/Menu/PopUpSpawner.cs
  Reabilitacao-Motora/Assets/Scripts/Menu/PopUpSpawner.cs.meta
  Reabilitacao-Motora/ProjectSettings/EditorBuildSettings.asset
Labels: Em Atraso, Front-End, MDS, Stack Overflow

#159 Resultado Sprint 08 e Roadmap da R2
  docs/imagens/Burndown/Sprint_08.png
  docs/imagens/Daily/Sprint08.png
  docs/imagens/Quadro de Conhecimento/Quadro_Conhecimento_08.png
  docs/imagens/Quadro de Praticas Ageis/Quadro_de_Praticas_Ageis_Sprint08.png
  docs/imagens/Retrospectiva/Retrospectiva_Sprint08.png
  docs/sprints/Resultado-Sprint-7.md
  docs/sprints/Resultado-Sprint-8.md
  docs/wiki/Roadmap.md
Labels: Documentação, EPS, Scrum Master

#167 Implementação do Sistema de Deploy Contínuo
  .travis.yml
  Reabilitacao-Motora/Assets/Scripts/travis_build.sh
  Reabilitacao-Motora/Assets/Scripts/travis_deploy_dev.sh
  Reabilitacao-Motora/Assets/Scripts/travis_deploy_master.sh
  Reabilitacao-Motora/Assets/Scripts/travis_tests.sh
Labels: DevOps, EPS, Ponto Crítico

#165 Pesquisar propostas de implementação TCP/UDP para central de processamento.
  docs/wiki/TCP_UDP.md
Labels: MDS, Noob

#163 Refatorar documento de arquitetura
  docs/wiki/Documento-de-Arquitetura.md
Labels: Arquitetura, MDS, Noob

#168 Adição da verificação de Testes na Integração Contínua
  .travis.yml
  Reabilitacao-Motora/Assets/Scripts/travis_build.sh
  Reabilitacao-Motora/Assets/Scripts/travis_tests.sh
  Reabilitacao-Motora/Assets/Scripts/travis_unity_key.sh
  Reabilitacao-Motora/Assets/Scripts/travis_unity_return_key.sh
  Reabilitacao-Motora/Assets/Scripts/travis_validation.sh
Labels: Aprimoramento, DevOps, Stack Overflow

#187 Resultado da Sprint 10 e Planejamento da Sprint 11
  docs/imagens/Burndown/Sprint_10.png
  docs/imagens/Daily/Sprint10.png
  docs/imagens/Quadro de Conhecimento/Quadro_Conhecimento_10.png
  docs/imagens/Quadro de Praticas Ageis/Quadro_de_Praticas_Ageis_Sprint10.png
  docs/imagens/Retrospectiva/Restrospectiva_Sprint10.png
  docs/sprints/Planejamento-Sprint-11.md
  docs/sprints/Resultado-Sprint-10.md
Labels: Documentação, EPS
