Repository fga-gpp-mds/2018.1-Reabilitacao-Motora, pull requests merged in 2018-03, with the labels that each got.

#23 Resultado Sprint 00
  docs/imagens/Quadro_Conhecimento_00.png
  docs/sprints/Planejamento-Sprint-0.md
  docs/sprints/Planejamento-Sprint-1.md
  docs/sprints/Planejamento-Sprint-2.md
  docs/sprints/Planejamento-Sprint-3.md
  docs/sprints/Planejamento-Sprint-4.md
  docs/sprints/Planejamento-Sprint-5.md
  docs/sprints/Planejamento-Sprint-6.md
  docs/sprints/Planejamento-Sprint-7.md
  docs/sprints/Planejamento-Sprint-8.md
  docs/sprints/Resultado-Sprint-0.md
  docs/sprints/Resultado-Sprint-1.md
  docs/sprints/Resultado-Sprint-2.md
  docs/sprints/Resultado-Sprint-3.md
  docs/sprints/Resultado-Sprint-4.md
  docs/sprints/Resultado-Sprint-5.md
  docs/sprints/Resultado-Sprint-6.md
  docs/sprints/Resultado-Sprint-7.md
  docs/sprints/Resultado-Sprint-8.md
  docs/sprints/Resultado-Sprint-Template.md
Labels: Documentação

#24 Organização das Sprints 00 e 01
  LICENSE.md
  README.md
  docs/imagens/grupo/Alexandre_Djorkaeff.png
  docs/imagens/grupo/Arthur_Diniz.png
  docs/imagens/grupo/Guilherme_Siqueira.png
  docs/imagens/grupo/Guilherme_de_Lyra.png
  docs/imagens/grupo/João_Lucas.png
  docs/imagens/grupo/Lucas_Malta.png
  docs/imagens/grupo/Romeu_Antunes.png
  docs/imagens/grupo/Victor_Moura.png
  docs/imagens/grupo/Vitor_Falcão.png
  docs/sprints/Planejamento-Sprint-0.md
  docs/sprints/Planejamento-Sprint-1.md
  docs/sprints/Planejamento-Sprint-2.md
  docs/sprints/Planejamento-Sprint-4.md
  docs/sprints/Planejamento-Sprint-5.md
  docs/sprints/Planejamento-Sprint-6.md
  docs/sprints/Planejamento-Sprint-7.md
  docs/sprints/Planejamento-Sprint-8.md
  docs/sprints/Resultado-Sprint-0.md
Labels: Aprimoramento, Documentação

#26 Organizar wiki e pasta docs do repositório
  docs/imagens/grupo/Davi_Alves.png
  docs/wiki/Branch.md
  docs/wiki/Commits.md
  docs/wiki/Documento-de-Visão.md
  docs/wiki/Dojo-C#.md
  docs/wiki/Dojo-Unity.md
  docs/wiki/Doxygen-Documentação-e-Exemplos.md
  docs/wiki/Doxygen-Instalação-e-Execução.md
  docs/wiki/Home.md
  docs/wiki/Issue.md
  docs/wiki/Pull-Request.md
  docs/wiki/Style-Sheet.md
  docs/wiki/_Sidebar.md
Labels: Aprimoramento, Documentação

#44 Resultado e Planejamento de Sprints
  docs/documento_de_visao.md
  docs/imagens/Quadro de Conhecimento/Quadro_Conhecimento_00.png
  docs/imagens/Quadro de Conhecimento/Quadro_Conhecimento_01.png
  docs/imagens/Quadro de Pareamento/Quadro_de_Pareamento.png
  docs/imagens/Quadro de Pareamento/Quadro_de_Pareamento.xml
  docs/imagens/Retrospectiva/Retrospectiva_Sprint01.png
  docs/imagens/grupo/Alexandre_Djorkaeff_50px.png
  docs/imagens/grupo/Arthur_Diniz_50px.png
  docs/imagens/grupo/Davi_Alves_50px.png
  docs/imagens/grupo/Forever_Alone.png
  docs/imagens/grupo/Forever_Alone_50px.png
  docs/imagens/grupo/Guilherme_Siqueira_50px.png
  docs/imagens/grupo/Guilherme_de_Lyra_50px.png
  docs/imagens/grupo/João_Lucas_50px.png
  docs/imagens/grupo/Lucas_Malta_50px.png
  docs/imagens/grupo/Romeu_Antunes_50px.png
  docs/imagens/grupo/Victor_Moura_50px.png
  docs/imagens/grupo/Vitor_Falcão_50px.png
  docs/sprints/Planejamento-Sprint-2.md
  docs/sprints/Resultado-Sprint-0.md
  docs/sprints/Resultado-Sprint-1.md
  docs/wiki/Roadmap.md
Labels: Documentação

#41 US14 - Menu do Sistema
  .gitignore
  Reabilitação-Motora/Assets/Imgs.meta
  Reabilitação-Motora/Assets/Imgs/background.jpg
  Reabilitação-Motora/Assets/Imgs/background.jpg.meta
  Reabilitação-Motora/Assets/Imgs/logo.png
  Reabilitação-Motora/Assets/Imgs/logo.png.meta
  Reabilitação-Motora/Assets/Prefabs.meta
  Reabilitação-Motora/Assets/Prefabs/SF Scene Elements.prefab
  Reabilitação-Motora/Assets/Prefabs/SF Scene Elements.prefab.meta
  Reabilitação-Motora/Assets/Scenes.meta
  Reabilitação-Motora/Assets/Scenes/Menu.unity
  Reabilitação-Motora/Assets/Scenes/Menu.unity.meta
  Reabilitação-Motora/Assets/Scenes/NotImplemented.unity
  Reabilitação-Motora/Assets/Scenes/NotImplemented.unity.meta
  Reabilitação-Motora/Assets/Scripts.meta
  Reabilitação-Motora/Assets/Scripts/Flow.cs
  Reabilitação-Motora/Assets/Scripts/Flow.cs.meta
  Reabilitação-Motora/Assets/Scripts/ScaleBackground.cs
  Reabilitação-Motora/Assets/Scripts/ScaleBackground.cs.meta
  Reabilitação-Motora/ProjectSettings/AudioManager.asset
  Reabilitação-Motora/ProjectSettings/ClusterInputManager.asset
  Reabilitação-Motora/ProjectSettings/DynamicsManager.asset
  Reabilitação-Motora/ProjectSettings/EditorBuildSettings.asset
  Reabilitação-Motora/ProjectSettings/EditorSettings.asset
  Reabilitação-Motora/ProjectSettings/GraphicsSettings.asset
  Reabilitação-Motora/ProjectSettings/InputManager.asset
  Reabilitação-Motora/ProjectSettings/NavMeshAreas.asset
  Reabilitação-Motora/ProjectSettings/NetworkManager.asset
  Reabilitação-Motora/ProjectSettings/Physics2DSettings.asset
  Reabilitação-Motora/ProjectSettings/ProjectSettings.asset
  Reabilitação-Motora/ProjectSettings/ProjectVersion.txt
  Reabilitação-Motora/ProjectSettings/QualitySettings.asset
  Reabilitação-Motora/ProjectSettings/TagManager.asset
  Reabilitação-Motora/ProjectSettings/TimeManager.asset
  Reabilitação-Motora/ProjectSettings/UnityConnectSettings.asset
  Reabilitação-Motora/UnityPackageManager/manifest.json
  Reabilitação-Motora/ProjectSettings/EditorBuildSettings.asset
Labels: Atenção Necessária, Codigo, Noob

#53 Criação do Código de Conduta
  .github/CODE_OF_CONDUCT.md
Labels: Agil, Aprimoramento, Atenção Necessária, Criar Issue do Pull Request, Documentação, EPS, Em Atraso, Necessitando Alterações, Pull Request Avaliado

#51 Correção da folha de estilo
  docs/wiki/Style-Sheet.md
Labels: Agil, Aprimoramento, Atenção Necessária, Documentação, EPS, Necessitando Alterações, Pull Request Avaliado

#56 Atualização dos Documentos de EPS
  .github/CODE_OF_CONDUCT.md
  docs/wiki/Style-Sheet.md
  docs/wiki/Termo-Abertura-Projeto.md
Labels: Agil, Documentação, EPS

#59 Criação das instruções de contribuição
  docs/contributing.md
Labels: Agil, Aprimoramento, Documentação, EPS, Noob

#67 Roadmap Release 1
  docs/wiki/Roadmap.md
Labels: Agil, Documentação, EPS, Em Atraso, Priorizar

#68 Atualização de Planejamento e Resultado
  .github/PULL_REQUEST_TEMPLATE.md
  docs/imagens/Burndown/Sprint_00.png
  docs/imagens/Burndown/Sprint_01.png
  docs/imagens/Burndown/Sprint_02.png
  docs/imagens/Quadro de Conhecimento/Quadro_Conhecimento_02.png
  docs/imagens/Retrospectiva/Retrospectiva_Sprint02.png
  docs/sprints/Planejamento-Sprint-0.md
  docs/sprints/Planejamento-Sprint-1.md
  docs/sprints/Planejamento-Sprint-2.md
  docs/sprints/Planejamento-Sprint-3.md
  docs/sprints/Resultado-Sprint-0.md
  docs/sprints/Resultado-Sprint-1.md
  docs/sprints/Resultado-Sprint-2.md
  docs/wiki/Metodologia.md
Labels: Agil, Aprimoramento, Atenção Necessária, Documentação, EPS, Em Atraso

#65 ME-R
  Banco_de_Dados/DER.png
  Banco_de_Dados/MER.md
  Banco_de_Dados/der.brM
Labels: Atenção Necessária, MDS
